"""dedup lookup index

Revision ID: 7ba9686c4678
Revises: 7e5c3be6d419
Create Date: 2026-08-24 13:57:49.084589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba9686c4678'
down_revision: Union[str, Sequence[str], None] = '7e5c3be6d419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.create_index('ix_records_sourcefile_identity', ['source_file', 'identity_hash'], unique=False)

    # ### end Alembic commands ###

    # Free-text search does ILIKE '%term%' across 13 columns, which no B-tree
    # can serve. These GIN trigram indexes are what make that search usable and
    # previously existed only if someone remembered to run
    # scripts/enable_trigram_search_indexes.py by hand against production.
    # PostgreSQL only; SQLite skips them and falls back to a scan.
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    for col in ("name", "community", "building_cluster", "developer",
                "project", "mobile_1"):
        op.execute(
            f"CREATE INDEX IF NOT EXISTS idx_records_{col}_trgm "
            f"ON records USING gin ({col} gin_trgm_ops)"
        )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_records_status_community_dev "
        "ON records (status, community, developer)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for col in ("name", "community", "building_cluster", "developer",
                    "project", "mobile_1"):
            op.execute(f"DROP INDEX IF EXISTS idx_records_{col}_trgm")
        op.execute("DROP INDEX IF EXISTS idx_records_status_community_dev")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_index('ix_records_sourcefile_identity')

    # ### end Alembic commands ###
