"""baseline schema

Revision ID: 8fd7756ae068
Revises: 
Create Date: 2026-08-24 13:51:52.677973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd7756ae068'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('stored_path', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('detected_format', sa.String(length=32), nullable=True),
    sa.Column('sheet_count', sa.Integer(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_files_content_sha256'), ['content_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_files_filename'), ['filename'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('can_export', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('export_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=320), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('filter_criteria', sa.JSON(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_audit_logs_exported_at'), ['exported_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_audit_logs_user_email'), ['user_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('invalid_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('skipped_rows', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('current_sheet', sa.String(length=255), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('mapping_report', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_jobs_source_file_id'), ['source_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_status'), ['status'], unique=False)

    op.create_table('processing_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('batch_number', sa.Integer(), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_errors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_errors_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_errors_job_id'), ['job_id'], unique=False)

    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('community', sa.String(length=255), nullable=True),
    sa.Column('sub_community', sa.String(length=255), nullable=True),
    sa.Column('building_cluster', sa.String(length=255), nullable=True),
    sa.Column('unit_number', sa.String(length=128), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('plot_reg_no', sa.String(length=128), nullable=True),
    sa.Column('plot_number', sa.String(length=128), nullable=True),
    sa.Column('dmno', sa.String(length=64), nullable=True),
    sa.Column('dmsubno', sa.String(length=64), nullable=True),
    sa.Column('bedroom', sa.String(length=64), nullable=True),
    sa.Column('party_type', sa.String(length=32), nullable=True),
    sa.Column('mobile_1', sa.String(length=32), nullable=True),
    sa.Column('mobile_2', sa.String(length=32), nullable=True),
    sa.Column('mobile_3', sa.String(length=32), nullable=True),
    sa.Column('email_address', sa.String(length=320), nullable=True),
    sa.Column('pi_number', sa.String(length=64), nullable=True),
    sa.Column('nationality', sa.String(length=128), nullable=True),
    sa.Column('property_type', sa.String(length=128), nullable=True),
    sa.Column('record_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('procedure_value', sa.Float(), nullable=True),
    sa.Column('developer', sa.String(length=255), nullable=True),
    sa.Column('project', sa.String(length=255), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('source_sheet', sa.String(length=255), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('identity_hash', sa.String(length=64), nullable=False),
    sa.Column('fuzzy_match_score', sa.Float(), nullable=True),
    sa.Column('fuzzy_matched_id', sa.Integer(), nullable=True),
    sa.Column('validation_flags', sa.JSON(), nullable=True),
    sa.Column('enriched_fields', sa.JSON(), nullable=True),
    sa.Column('owner_count', sa.Integer(), nullable=True),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_records_bedroom'), ['bedroom'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_building_cluster'), ['building_cluster'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_community'), ['community'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_developer'), ['developer'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_email_address'), ['email_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_identity_hash'), ['identity_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_records_job_status', ['job_id', 'status'], unique=False)
        batch_op.create_index('ix_records_location', ['community', 'building_cluster', 'unit_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_mobile_1'), ['mobile_1'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_party_type'), ['party_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_pi_number'), ['pi_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_plot_number'), ['plot_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_project'), ['project'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_property_type'), ['property_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_source_file'), ['source_file'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_sub_community'), ['sub_community'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_unit_number'), ['unit_number'], unique=False)

    op.create_table('record_edits_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=320), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('record_edits_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_record_edits_audit_edited_at'), ['edited_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_edits_audit_field_name'), ['field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_edits_audit_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_edits_audit_user_email'), ['user_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_edits_audit_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_edits_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_record_edits_audit_user_id'))
        batch_op.drop_index(batch_op.f('ix_record_edits_audit_user_email'))
        batch_op.drop_index(batch_op.f('ix_record_edits_audit_record_id'))
        batch_op.drop_index(batch_op.f('ix_record_edits_audit_field_name'))
        batch_op.drop_index(batch_op.f('ix_record_edits_audit_edited_at'))

    op.drop_table('record_edits_audit')
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_records_unit_number'))
        batch_op.drop_index(batch_op.f('ix_records_sub_community'))
        batch_op.drop_index(batch_op.f('ix_records_status'))
        batch_op.drop_index(batch_op.f('ix_records_source_file'))
        batch_op.drop_index(batch_op.f('ix_records_property_type'))
        batch_op.drop_index(batch_op.f('ix_records_project'))
        batch_op.drop_index(batch_op.f('ix_records_plot_number'))
        batch_op.drop_index(batch_op.f('ix_records_pi_number'))
        batch_op.drop_index(batch_op.f('ix_records_party_type'))
        batch_op.drop_index(batch_op.f('ix_records_name'))
        batch_op.drop_index(batch_op.f('ix_records_mobile_1'))
        batch_op.drop_index('ix_records_location')
        batch_op.drop_index('ix_records_job_status')
        batch_op.drop_index(batch_op.f('ix_records_job_id'))
        batch_op.drop_index(batch_op.f('ix_records_identity_hash'))
        batch_op.drop_index(batch_op.f('ix_records_email_address'))
        batch_op.drop_index(batch_op.f('ix_records_developer'))
        batch_op.drop_index(batch_op.f('ix_records_community'))
        batch_op.drop_index(batch_op.f('ix_records_building_cluster'))
        batch_op.drop_index(batch_op.f('ix_records_bedroom'))

    op.drop_table('records')
    with op.batch_alter_table('processing_errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_errors_job_id'))
        batch_op.drop_index(batch_op.f('ix_processing_errors_code'))

    op.drop_table('processing_errors')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_source_file_id'))

    op.drop_table('processing_jobs')
    with op.batch_alter_table('export_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_export_audit_logs_user_email'))
        batch_op.drop_index(batch_op.f('ix_export_audit_logs_exported_at'))

    op.drop_table('export_audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('source_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_files_filename'))
        batch_op.drop_index(batch_op.f('ix_source_files_content_sha256'))

    op.drop_table('source_files')
    # ### end Alembic commands ###
